#Server Port
server:
  port: 8765

#EUREKA
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

#Ribbon Activation
ribbon:
  eureka:
    enabled: true